### ISSUE TITLE
npm install shows error for not having a repository field

### ISSUE THREAD

**Issue by ilanbiala** [cainus/sinon-restore#1]
npm WARN package.json sinon-restore@1.0.0 No repository field.

**Comment by cainus** [comment]
fixed in 1.0.1!  Thanks!

**Comment by ilanbiala** [comment]
Thanks for that! It seems like this is such a small amount of code. Does it overwrite anything in Sinon itself or just add on top of the package? I'm thinking it would be better for a bunch of people of it were combined because it would reduce the number of dependencies and that way more people know about it and can use it.

**Comment by cainus** [comment]
Yeah it's tiny and additive.  I suspect they wouldn't be interested in implementing it though, because they've already got a different solution.

**Comment by ilanbiala** [comment]
Hmm is it possible to either switch to sinon's solution or for them to accept yours? I just think it is complicated and can be simplified.

**Comment by cainus** [comment]
Hmmm... not sure I understand you... What do you think is complicated?

**Comment by ilanbiala** [comment]
I just think that having multiple things that do the same simple task makes for a lot of clutter and possible issues in the compatibility and complicated for people to decide which one to use and maybe the don't even know about yours.

**Comment by cainus** [comment]
Ha well you don't have to use this library.  ;)  I can't unpublish it though.  ;)

**Comment by ilanbiala** [comment]
I think this is a dependency for node-coveralls, so I'm just trying to lighten the load for you and for others. I appreciate everything you're doing.

**Comment by cainus** [comment]
It's a dev dependency only of logdriver, so it doesn't get installed with node-coveralls.  If you really want to eliminate it though, I'm open to a PR where the logdriver tests use pure sinon.  If you did that, you'd see why I like my solution better too. ;)
